[package]
name = "simple_sha256"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
hex = "0.4.3"
rand = "0.8.5"

[[bench]]
name = "my_bench"
harness = false
